### ISSUE TITLE
Refactor Song Model

### ISSUE THREAD

**Issue by afpola** [afpola/first_website#7]
Should model one chord used in a song (show the strings, frets etc).

**Comment by afpola** [comment]
Hmm, isn't this supposed to show all the chords used? Or is that a separate component. It's not the other issue: Riff component. Have to think about this a bit more.

**Comment by afpatmin** [comment]
Instead of a separate [Chord] model, add a new member variable to [Song] `Map<String, String> choords` where map keys are choord names ('Dm', 'A', etc) and map values are the choord values ('x012345')

**Comment by afpatmin** [comment]
Also we should rename some of the fields in [Song], 'songTitle' should be just 'title', and 'data' should be something else ('lyrics'?)

I suggest we update the issue title to 'Refactor Song Model'
